# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='unknown', max_length=12),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course_num',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='dept',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='instructor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='room',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
