# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170316_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.CharField(default='unknown', max_length=8),
        ),
    ]
